name = "gridiron-wallet"
type = "webpack"
zone_id = '000fde296cba847a78e918414382ba7a'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-08"

[env.testnet-staging]
routes = ["https://test.wallet.furya.app/*"]

[env.mainnet-staging]
routes = ["https://staging.wallet.furya.app/*"]

[env.release]
routes = ["https://wallet.furya.app/*"]